### ISSUE TITLE
Using Filters does not filter current search, rather it starts a new search

### ISSUE THREAD

**Issue by lcanizzo** [Ankitashah212/School_guide#32]

**Comment by Ankitashah212** [comment]
yupp , that's the way I designed the queries with initial design. With new design, let me update the logic

**Comment by Ankitashah212** [comment]
I looked into it, it does filter, it's a new Ajax call but that should not matter. let's talk about it tomorrow

**Comment by Ankitashah212** [comment]
resolved.
